[2.175s] Invoking command in '/home/luiz/2D_mapping/build/2d_mapping': PYTHONPATH=/home/luiz/2D_mapping/build/2d_mapping/prefix_override:/home/luiz/2D_mapping/install/2d_mapping/lib/python3.10/site-packages: /usr/bin/python3 setup.py develop --uninstall --editable --build-directory /home/luiz/2D_mapping/build/2d_mapping/build
[2.222s] /usr/bin/python3: can't open file '/home/luiz/2D_mapping/build/2d_mapping/setup.py': [Errno 2] No such file or directory
[2.233s] Invoked command in '/home/luiz/2D_mapping/build/2d_mapping' returned '2': PYTHONPATH=/home/luiz/2D_mapping/build/2d_mapping/prefix_override:/home/luiz/2D_mapping/install/2d_mapping/lib/python3.10/site-packages: /usr/bin/python3 setup.py develop --uninstall --editable --build-directory /home/luiz/2D_mapping/build/2d_mapping/build
